### PR TITLE
Graphql-yoga to apollo-server-express

### PR DESCRIPTION
**Pull request by XshubhamX**
- **Please check if the PR fulfills these requirements**

* [yes ] The commit message follows our guidelines
* [not required ] Tests for the changes have been added (for bug fixes / features)
* [ no] Docs have been added / updated (for bug fixes / features)

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- server changed

### CODE REVIEW

**Review by XshubhamX — COMMENTED** [review]
Waiting for 1 reviewer

**Comment by XshubhamX** [comment]
@jasbirrajrana plz review the pr

**Review by jasbirrajrana — APPROVED** [review]
@XshubhamX  You can add your server dist folder into the `.gitignore` file.

**Review by jasbirrajrana — APPROVED** [review]
@XshubhamX seems to be good migration from `graphql-yoga` to `apollo-express-server` 🚀

**Pull request merged**
